feat(PLT-271): add cache to finance core api
brighte-capital/brighte-api-sdk-php pull request #31
Opened 2022-03-21 23:34 UTC by barkerxuan

This PR adds cache to finance core API

2022-03-22 04:55 UTC, darkbluesun requested changes
Hi Barker
This is good work, but I have two critical things that need fixing first, inline comments below
Also, had you considered adding this functionality to the BrighteApi class? and if so, why did you decide against it?

2022-03-22 04:55 UTC, darkbluesun commented on src/FinanceCoreApi.php
> +    public function __construct(LoggerInterface $logger, BrighteApi $brighteApi, CacheItemPoolInterface $cache)
in order to not break clients, you should make CacheItemPoolInterface nullable with a `?`

2022-03-22 04:55 UTC, darkbluesun commented on src/FinanceCoreApi.php
> +        if ($cachedItem = $this->cacheItemPool->getItem($key)) {
you should handle if `$this->cacheItemPool` is null

2022-03-22 05:16 UTC, barkerxuan commented
@darkbluesun I think it is doable, but I was under the impression that BrighteApi serves as a shared class that will be used by other classes. The cached function is quite specific to the finance core(Graphql) as we cache the response of post requests. We could add a new function like `cachedPost` in BrighteApi, do you think that is a better approach?

2022-03-22 05:24 UTC, darkbluesun commented
Yeah if you don't mind barker, I think a cachedPost in brighteApi would be much better because I think we will get more graphql apis over time and this will become a thing. The only way it's specific to the financecore api is just that it's post instead of get.

2022-03-23 04:28 UTC, darkbluesun commented on src/BrighteApi.php
> +        string $functionName,
maybe instead of using these as input, just take the string $key as input here, as with getCached.

2022-03-23 04:39 UTC, darkbluesun approved these changes
Looking good 👍

2022-03-23 05:37 UTC, hbhrugubanda approved these changes
Looks good! 💯  No blocking comments, however please wait for Chris to approve as well ✅

2022-03-23 05:37 UTC, hbhrugubanda commented on src/BrighteApi.php
> +            $expires = new \DateInterval('PT' . strtoupper("15m"));
question: out of curiosity, how did we come up with 15 mins?

2022-03-23 05:37 UTC, hbhrugubanda commented on tests/FinanceCoreApiTest.php
> +    public function testgetFinancialProductConfigWhenReturnsNull(): void
```suggestion
    public function testGetFinancialProductConfigWhenReturnsNull(): void
```

2022-03-23 05:37 UTC, hbhrugubanda commented on tests/FinanceCoreApiTest.php
> +    public function testgetFinancialProductWhenReturnsNull(): void
```suggestion
    public function testGetFinancialProductWhenReturnsNull(): void
```

2022-03-23 05:41 UTC, darkbluesun approved these changes

2022-03-23 22:25 UTC, merged