feat(NGMA-1113): add getCategoryById query
brighte-capital/brighte-api-sdk-php pull request #55
Opened 2023-02-20 05:07 UTC by Willbrighte

Added getCategoryById to finance core api.

2023-02-20 21:21 UTC, fahadbrighte submitted a review, later dismissed

2023-02-20 21:27 UTC, christheyounger requested changes
Looking good, but I ask please for a couple of small changes. thanks

2023-02-20 21:27 UTC, christheyounger commented on src/FinanceCoreApi.php
> +            query {
suggestion: add a name for this query and input definitions as per convention
```
query GetCategory($categoryId: Int!) {
````

2023-02-20 21:27 UTC, christheyounger commented on src/FinanceCoreApi.php
> +                    isVirtualPowerPlantCompatible
question: you've requested a lot of properties that you don't set on the output of the function. should we remove them?

2023-02-20 21:28 UTC, christheyounger requested changes
Looking good, but I ask please for a couple of small changes. thanks

2023-02-20 21:29 UTC, Willbrighte commented on src/FinanceCoreApi.php
> +                    isVirtualPowerPlantCompatible
Will remove them, thanks Chris.

2023-02-20 21:29 UTC, Willbrighte commented on src/FinanceCoreApi.php
> +            query {
Will update.

2023-02-21 01:18 UTC, fahadbrighte approved these changes

2023-02-21 01:54 UTC, christheyounger approved these changes

2023-02-21 02:07 UTC, merged