Feature bh 6199 promotion api
brighte-capital/brighte-api-sdk-php pull request #7
Opened 2020-08-25 08:39 UTC by afareh

2020-08-25 22:58 UTC, darkbluesun requested changes
Hi Ali
This looks pretty good. I like the use of exceptions.
Can I suggest, maybe those generic looking exceptions (e.g. RecordNotFoundException) shouldn't really extend the PromotionException, since they could, should be used for other apis
I noticed you wrote tests, but got zero coverage. You can run `composer test:coverage` to get the metrics. That will give you a number in the console, and generate coverage.xml that you can read with your IDE. You are missing the @covers annotations.
Thanks

2020-08-25 22:58 UTC, darkbluesun commented on src/Promotion/PromotionApi.php
> +            return json_decode((string)$response->getBody());
Hi Ali, it would be good if this function returned a Promotion entity, rather than a stdclass.

2020-08-25 22:58 UTC, darkbluesun commented on src/Promotion/Exceptions/RecordNotFoundException.php
> +class RecordNotFoundException extends PromotionException
this seems like a generic exception that all the apis could use, so why extend PromotionException?

2020-08-25 22:58 UTC, darkbluesun commented on tests/Promotion/PromotionApiTest.php
> +    public function testApplyPromotionThrowGenericException()
these functions need `@covers` annotations
run `composer test:coverage` to get the report in text as well as coverage.xml that you can read with an IDE plugin.

2020-08-25 23:49 UTC, afareh commented on src/Promotion/Exceptions/RecordNotFoundException.php
> +class RecordNotFoundException extends PromotionException
That's a good idea, Chris. I  will update it.

2020-08-25 23:52 UTC, afareh commented on src/Promotion/PromotionApi.php
> +            return json_decode((string)$response->getBody());
I agree with you Chris, I wasn't 100% of the Promotion Entity shape and that's why I left it for now. I will see if I can figure that out.

2020-08-26 01:53 UTC, afareh commented on tests/Promotion/PromotionApiTest.php
> +    public function testApplyPromotionThrowGenericException()
Thanks Chris regarding the usage of the annotation,  haven't used them before. Happy to get some feedback on it.

2020-08-26 02:05 UTC, darkbluesun commented on tests/Promotion/PromotionApiTest.php
> +    public function testApplyPromotionThrowGenericException()
you've done it perfectly. if there's anything that you aren't really testing, but that causes an error otherwise, you can use the `@uses` tag, to indicate that you're not really trying to test that file, it's just a side-effect.

2020-08-26 02:37 UTC, kaleongchan commented on src/Promotion/Exceptions/BadRequestException.php
> +class BadRequestException extends PromotionException
I guess you missed this one.

2020-08-26 02:38 UTC, kaleongchan commented on src/Promotion/Exceptions/BadRequestException.php
> +use Throwable;
Is `Throwable` used?

2020-08-26 04:45 UTC, afareh commented on src/Promotion/Exceptions/BadRequestException.php
> +class BadRequestException extends PromotionException
Thanks Ka, good catch.

2020-08-26 04:49 UTC, darkbluesun approved these changes
Nice Job Ali

2020-08-26 05:18 UTC, darkbluesun commented on composer.json
> +        "json-mapper/json-mapper": "^1.3"
json-mapper/json-mapper 1.3.0 requires php ^7.2 || ^8.0 -> your PHP version (7.1.27) does not satisfy that requirement.

2020-08-26 05:23 UTC, afareh commented on composer.json
> +        "json-mapper/json-mapper": "^1.3"
Oh damn. I forgot to check. I will remove it and see if there are alternative otherwise I will do the mapping the hard way :(

2020-08-26 05:43 UTC, afareh commented on composer.json
> +        "json-mapper/json-mapper": "^1.3"
I found this one which does the same thing. What do you guys think? https://packagist.org/packages/averor/json-mapper

2020-08-26 06:08 UTC, darkbluesun commented on composer.json
> +        "json-mapper/json-mapper": "^1.3"
looks good to me. it obviously does the trick

2020-08-26 06:09 UTC, darkbluesun submitted a review, later dismissed
Looking good, just need that last mile of coverage

2020-08-26 07:37 UTC, lilianfan-brighte commented on src/Promotion/PromotionApi.php
> +        $response = $this->brighteApi->get(sprintf('%s/%s', self::PATH, $id));
I don't think we're implementing `GET /promotions/[promoCode]` at this stage.  The endpoint should be `GET /promotions` with the ability to search by vendor and/or product type.

The immediate usage of this endpoint will be to retrieve any active promotions by vendor, e.g. Joe logs into portal, and he belongs to vendors SolarFlower - if SolarFlower has any active promotions, Joe should see banners for them.

2020-08-26 07:48 UTC, lilianfan-brighte commented on src/Promotion/Models/ApplicationPromotion.php
> +    public $promotionId;
You shouldn't have the promotion Id at this stage - portal itself shouldn't know anything about promotions any more.  `POST /promotions/applications` decides whether a promotion applies to the application, and returns a promotion (or not).

2020-08-26 07:55 UTC, lilianfan-brighte commented on src/Promotion/Models/Promotion.php
> +    public $type_id;
Looks like it might be `promotion_type_id` and a uuid type - but unsure this will be useful information to return either way.

2020-08-27 23:08 UTC, afareh commented on src/Promotion/PromotionApi.php
> +        $response = $this->brighteApi->get(sprintf('%s/%s', self::PATH, $id));
Good catch Lilian. I have added that in now.

2020-08-27 23:10 UTC, afareh commented on src/Promotion/Models/Promotion.php
> +    public $type_id;
I didn't add 'promotion' because the entity name is Promotion so that was my thinking.

2020-08-27 23:15 UTC, afareh commented on src/Promotion/Models/ApplicationPromotion.php
> +    public $promotionId;
That makes sense but what if the vendor has two active promotions for the same product? Can we hop on a quick call after stand up so we are all in alignment?

2020-08-28 01:15 UTC, darkbluesun requested changes
Looking good Ali. Just not sure about the return value from ApplyPromotion. I commented inline.

2020-08-28 01:15 UTC, darkbluesun commented on src/Promotion/PromotionApi.php
> +            return $this->jsonMapper::map($applicationPromotionResponse, Promotion::class);
I apologise for misleading statements I made earlier
I think the response from this API endpoint will be an ApplicationPromotion?
In which case that is what we should return from this function?

2020-08-28 01:25 UTC, darkbluesun commented on src/Promotion/PromotionApi.php
> +            $applicationPromotionResponse = $response->getBody();
is this a superflous variable? could you just add `$response->getBody()` on line 43?

2020-08-28 02:28 UTC, afareh commented on src/Promotion/PromotionApi.php
> +            return $this->jsonMapper::map($applicationPromotionResponse, Promotion::class);
Thats good point Chris, but here why I went the other way. In the portal, we will try to apply the promotion to the application and send the promo code to Finpower. So returning ApplicationPromotion will result in two API calls in order to get the promo code and send it to Finpower. 

on the other hand, return AppicationPromotion is probably more in line with convention and I can make that change easily.


Thoughts.

2020-08-28 03:05 UTC, kaleongchan commented on src/Promotion/Models/ApplicationPromotion.php
> +class ApplicationPromotion
This is meant to capture the important bits of an application. I don't think its name should contain promotion at all. How about just Application?

2020-08-28 03:25 UTC, kaleongchan commented on src/Promotion/PromotionApi.php
> +            return $this->jsonMapper::map($response->getBody(), Promotion::class);
map is a static function meant to be called via class name JsonMapper::map(). It's not necessary to create an object to call the function.

Also from reading https://gitlab.com/Averor/json-mapper/-/blob/master/tests/JsonMapperTest.php#L192 This will throw exception that you might want to try/catch it.

2020-08-28 03:25 UTC, lilianfan-brighte commented on src/Promotion/Models/ApplicationPromotion.php
> +    public function __construct(int $applicationId, int $vendorId, string $product, $variant = null)
I think we'll be going by the application and vendor remote Ids - so they should both be strings?

2020-08-28 03:27 UTC, darkbluesun commented on src/Promotion/PromotionApi.php
> +            return $this->jsonMapper::map($applicationPromotionResponse, Promotion::class);
Ah, I see what you're going for there.
I think it all depends on the API spec for the promo engine, and I'd highly recommend for that part that when you post to /promotions/applications that you get an promotion/application back.
This explains why you had a get-promotion-by-id method in this sdk @lilianfan-brighte - because you'll want to get the promotion that was assigned.
I think it would be best to have a convenience method that posts the application, gets back the applicationpromotion, and then gets the promotion details back by doing a GET.
Two api calls is not an extreme measure to take, and it means the API is more RESTful

2020-08-28 03:32 UTC, darkbluesun commented on src/Promotion/PromotionApi.php
> +            return $this->jsonMapper::map($applicationPromotionResponse, Promotion::class);
on the other hand, maybe the promotion/application object should contain the promo ID _and_ the promo code? I know it's not fully normalized, but overnormalizing just makes things hard.

2020-08-28 05:25 UTC, kaleongchan commented on src/Promotion/Models/ApplicationPromotion.php
> +    public $product_variant;
What is it supposed to capture?

2020-08-28 05:51 UTC, afareh commented on src/Promotion/Models/ApplicationPromotion.php
> +    public $product_variant;
It's for that thing you said about the category this morning. e.g "BPL:HI".

2020-08-28 06:04 UTC, darkbluesun commented on src/Promotion/Models/ApplicationPromotion.php
> +    public $product_variant;
oh. I assumed it would store 'residential' or 'business'

2020-08-28 07:37 UTC, afareh commented on src/Promotion/PromotionApi.php
> +            return $this->jsonMapper::map($response->getBody(), Promotion::class);
okay thanks

2020-08-31 01:57 UTC, darkbluesun requested changes
thanks Ali, love how this is coming along, just a couple little things here

2020-08-31 01:57 UTC, darkbluesun commented on tests/Promotion/Models/ApplicationTest.php
> +            'code' => null
please add a code for this test

2020-08-31 01:57 UTC, darkbluesun commented on src/Promotion/Models/Promotion.php
> +    public $promotionTyped;
possible typo?

2020-08-31 01:57 UTC, darkbluesun commented on tests/Promotion/Models/PromotionTest.php
> +            'modified' => null,
please add dates to test

2020-08-31 01:58 UTC, darkbluesun commented on src/Promotion/Exceptions/BadRequestException.php
> +namespace BrighteCapital\Api\Promotion\Exceptions;
could this exception reside outside the promotion namespace?

2020-08-31 03:57 UTC, darkbluesun approved these changes
awesome thanks

2020-08-31 08:16 UTC, kaleongchan commented on src/Promotion/PromotionApi.php
> +    public function getPromotion(int $id): Promotion
string $id ?

2020-09-01 23:46 UTC, kaleongchan approved these changes
:+1:

2020-09-02 02:41 UTC, mohammed-fahad approved these changes

2020-09-07 03:16 UTC, darkbluesun approved these changes
:ok_hand:

2020-09-07 06:51 UTC, kaleongchan approved these changes
:+1:

2020-09-07 06:52 UTC, merged